// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Util from "./Util.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

async function make(props) {
  var match = await Util.getContentAndFrontmatter(props.params.name);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: "프로그래밍의 도를 향하여",
                      className: "text-3xl font-bold text-slate-800"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h1", {
                              children: match.frontmatter.title,
                              className: "text-2xl font-bold text-slate-800"
                            }),
                        JsxRuntime.jsx("article", {
                              children: match.content,
                              className: "prose dark:prose-invert text-justify max-w-xl mx-auto md:max-w-4xl"
                            })
                      ],
                      className: "flex flex-col gap-7"
                    })
              ],
              className: "flex flex-col gap-9 px-6 py-12 max-w-xl mx-auto md:max-w-4xl"
            });
}

var $$default = make;

export {
  make ,
  $$default as default,
}
/* Util Not a pure module */
