// Generated by ReScript, PLEASE EDIT WITH CARE

import Link from "next/link";
import * as ThemeChangeButton from "./ThemeChangeButton.res.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as NavigationMenu from "@/components/ui/navigation-menu";

function NavigationBar$ListItem(props) {
  return JsxRuntime.jsx(Link, {
              href: props.href,
              passHref: true,
              legacyBehavior: true,
              children: JsxRuntime.jsx(NavigationMenu.NavigationMenuLink, {
                    className: NavigationMenu.navigationMenuTriggerStyle() + " bg-transparent",
                    children: props.title
                  })
            });
}

var ListItem = {
  make: NavigationBar$ListItem
};

function NavigationBar(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsxs(Link, {
                            className: "text-lg sm:text-2xl lg:text-3xl font-bold",
                            href: "/",
                            children: [
                              "Seeking\u00A0the\u00A0Tao\u00A0of",
                              JsxRuntime.jsx("br", {}),
                              "Programming"
                            ]
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx(NavigationMenu.NavigationMenu, {
                                    children: JsxRuntime.jsx(NavigationMenu.NavigationMenuList, {
                                          children: JsxRuntime.jsx(NavigationMenu.NavigationMenuItem, {
                                                children: JsxRuntime.jsx(NavigationBar$ListItem, {
                                                      title: "About",
                                                      href: "/about"
                                                    })
                                              })
                                        })
                                  }),
                              JsxRuntime.jsx(ThemeChangeButton.make, {})
                            ],
                            className: "flex gap-2"
                          })
                    ],
                    className: "flex justify-between items-end gap-2 px-6 max-w-xl mx-auto md:max-w-2xl"
                  }),
              className: "sticky top-0 border-b border-stone-500 bg-background/80 backdrop-blur-lg py-2 mt-10"
            });
}

var make = NavigationBar;

export {
  ListItem ,
  make ,
}
/* next/link Not a pure module */
