// Generated by ReScript, PLEASE EDIT WITH CARE

import Link from "next/link";
import * as ThemeChangeButton from "./ThemeChangeButton.res.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as NavigationMenu from "@/components/ui/navigation-menu";

function NavigationBar$ListItem(props) {
  return JsxRuntime.jsx(Link, {
              href: props.href,
              passHref: true,
              legacyBehavior: true,
              children: JsxRuntime.jsx(NavigationMenu.NavigationMenuLink, {
                    className: NavigationMenu.navigationMenuTriggerStyle(),
                    children: props.title
                  })
            });
}

var ListItem = {
  make: NavigationBar$ListItem
};

function NavigationBar(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs(Link, {
                      className: "text-lg sm:text-2xl lg:text-3xl font-bold",
                      href: "/",
                      children: [
                        "Seeking\u00A0the\u00A0Tao\u00A0of",
                        JsxRuntime.jsx("br", {}),
                        "Programming"
                      ]
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx(NavigationMenu.NavigationMenu, {
                              children: JsxRuntime.jsxs(NavigationMenu.NavigationMenuList, {
                                    children: [
                                      JsxRuntime.jsx(NavigationMenu.NavigationMenuItem, {
                                            children: JsxRuntime.jsx(NavigationBar$ListItem, {
                                                  title: "Posts",
                                                  href: "/posts"
                                                })
                                          }),
                                      JsxRuntime.jsx(NavigationMenu.NavigationMenuItem, {
                                            children: JsxRuntime.jsx(NavigationBar$ListItem, {
                                                  title: "About",
                                                  href: "/about"
                                                })
                                          })
                                    ]
                                  })
                            }),
                        JsxRuntime.jsx(ThemeChangeButton.make, {})
                      ],
                      className: "flex gap-2"
                    })
              ],
              className: "flex justify-between items-end"
            });
}

var make = NavigationBar;

export {
  ListItem ,
  make ,
}
/* next/link Not a pure module */
