// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Util from "../shared/Util.res.js";
import * as JsxRuntime from "react/jsx-runtime";

function generateStaticParams() {
  return Util.getAllPostFileNames().map(function (file) {
              return {
                      name: file
                    };
            });
}

async function make(param) {
  var match = await Util.getContentAndFrontmatter(param.params.name);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: "프로그래밍의 도를 찾아서",
                      className: "text-2xl lg:text-3xl font-bold text-slate-800"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h1", {
                              children: match.frontmatter.title,
                              className: "text-2xl font-bold text-slate-800"
                            }),
                        JsxRuntime.jsx("article", {
                              children: match.content,
                              className: "prose dark:prose-invert text-justify max-w-xl mx-auto md:max-w-4xl"
                            })
                      ],
                      className: "flex flex-col gap-7"
                    })
              ],
              className: "flex flex-col gap-9 px-6 py-12 max-w-xl mx-auto md:max-w-4xl"
            });
}

var Post = make;

var make$1 = Post;

export {
  generateStaticParams ,
  make$1 as make,
}
/* Util Not a pure module */
