// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Util from "../shared/Util.res.js";
import * as JsxRuntime from "react/jsx-runtime";

function generateStaticParams() {
  return Util.getAllPostFileNames().map(function (file) {
              return {
                      name: file
                    };
            });
}

async function make(param) {
  var match = await param.params;
  var match$1 = await Util.getContentAndFrontmatter(match.name);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: match$1.frontmatter.title,
                      className: "text-2xl font-bold"
                    }),
                JsxRuntime.jsx("article", {
                      children: match$1.content,
                      className: "prose dark:prose-invert text-justify max-w-xl mx-auto md:max-w-4xl"
                    })
              ],
              className: "flex flex-col gap-7"
            });
}

var Post = make;

var make$1 = Post;

export {
  generateStaticParams ,
  make$1 as make,
}
/* Util Not a pure module */
