'use client';
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as NextThemes from "next-themes";
import * as JsxRuntime from "react/jsx-runtime";
import * as Button from "@/components/ui/button";

function ThemeChangeButton(props) {
  var match = React.useState(function () {
        return false;
      });
  var setMounted = match[1];
  var match$1 = NextThemes.useTheme();
  var setTheme = match$1.setTheme;
  var theme = match$1.theme;
  React.useEffect((function () {
          setMounted(function (param) {
                return true;
              });
        }), []);
  if (!match[0]) {
    return null;
  }
  var tmp = theme === "light" ? "🌙" : "☀️";
  return JsxRuntime.jsx(Button.Button, {
              variant: "ghost",
              size: "icon",
              onClick: (function (param) {
                  var tmp = theme === "light" ? "dark" : "light";
                  setTheme(tmp);
                }),
              children: tmp
            });
}

var make = ThemeChangeButton;

export {
  make ,
}
/* react Not a pure module */
