// Generated by ReScript, PLEASE EDIT WITH CARE


var NavigationMenu = {};

var NavigationMenuList = {};

var NavigationMenuItem = {};

var NavigationMenuTrigger = {};

var NavigationMenuContent = {};

var NavigationMenuLink = {};

export {
  NavigationMenu ,
  NavigationMenuList ,
  NavigationMenuItem ,
  NavigationMenuTrigger ,
  NavigationMenuContent ,
  NavigationMenuLink ,
}
/* No side effect */
